name: Release

on:
  workflow_dispatch:

jobs:
  build-marlin:
    runs-on: ubuntu-latest
    name: Build Marlin Firmware
    steps:

    - uses: actions/checkout@v2

    - id: build
      uses: Transmitt0r/build-marlin-action@v1.0.0

    - uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: ${{ steps.build.outputs.binary }}

    - uses: release-drafter/release-drafter@v5
      id: release
      with:
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Compiled Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.binary }}
        asset_name: marlin.bin
        asset_content_type: application/octet-stream